//
//  MaaS360SDKDelegate.h
//  MaaS360SDK
//
//  Created by Naresh SVS on 27/05/14.
//  Copyright (c) 2014 Fiberlink. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN
//
// Delegate protocol
//
@protocol MaaS360SDKDelegate <NSObject>

@required

// SDK state changed.
- (void)sdkStateChangedTo:(MaaS360SDKState)state;

// Compliance state changed.
- (void)complianceStateChangedTo:(M360SDKComplianceInfo *)complianceInfo;

// Restrict data sharing.
// Deprecated api. restrictDataSharingWithSettings. Delegate calls restrictDataSharingWithSettings if implemented
// otherwise calls restrictDataSharing:withWhiteListedApps
- (void)restrictDataSharing:(BOOL)on withWhiteListedApps:(nullable NSArray *)apps;

// Wipe data. The delegate is supposed to wipe the local data upon invoking this method.
- (void)wipeData;

// Revoke wiped data. The delegate is supposed to revoke the wiped local data.
- (void)revokeWipedData;

@optional

// Called when wew policy available.
- (void)newPolicyAvailable;

- (void)restrictDataSharingWithSettings:(M360SDKDocExportSetting *)docExportSettings;

// Called when policy entitlements are loaded for first time.
- (void)policyEntitlementsLoaded;

// Called when wew policy entitlements modified.
- (void)policyEntitlementsChanged;

// Enterprise gateway login successful.
- (void)EGLoginSuccessful;

// Enterprise gateway logout successful.
- (void)EGLogoutSuccessful;

// Enterprise gateway error.
- (void)EGErrorOccured:(NSString *) error;

// Enterprise gateway credentials
- (NSDictionary *)EGAuthCredentials;

// New Document available
- (void)newDocumentAvailable:(nullable M360SDKEditorDocContext *)docContext;

// Edited Document available
- (void)editedDocumentAvailable:(nullable M360SDKEditorDocContext *)docContext;

// Present configuring screen while enrolment is being done
- (void)presentEnrollmentUI:(UINavigationController *)controller;

// Dismiss the confguring screen on enrolment completion
- (void)dismissEnrollmentUI;

// SDK App Configuration Profile available
- (void)newConfigurationAvailable:(nullable NSData *)configData;

// Containerlockedstatus changed - app coming to foreground over activation of an SDK app
- (void)containerLockedStatusChanged;

// Errors generated by the SDK to inform the app about the issues.
- (void)errorProvidedByM360SDK:(NSError *) error;

// Change app verbose log level.
- (BOOL)setSdkVerboseLogLevelViaMDMAction:(BOOL)isVerboseEnabled;

// App log file path
- (void)collectAppLogFilePathViaMDMAction:(void (^__nullable)(NSString* filePath)) completionBlock;

- (void)handleTimeBasedOOCEventWith:(NSString *)reason;

- (void)dismissTimeBasedOOCEvent;

@end

NS_ASSUME_NONNULL_END
