export interface Dde {
    vehicleValuation?: VehicleValuation;
    pslData?: PslData;
}

export interface VehicleValuation {
    valuatorType?: string;
    valuatorCode?: string;
    valuatorName?: string;
    valuationAmount?: number;
    valuationDate?: string;
    idv?: string;
    idvValidityDate?: string;
    vhAvailInGrid?: string;
    gridAmount?: string;
    assetManufacturer?: string;
    assetModel?: string;
    newUsedAsset?: string;
    vechicleNoPrefix?: string;
    vechicleNumber?: string;
    chassisNumber?: string;
    engineNumber?: string;
    yearRegOfAsset?: string;
    monthRegOfAsset?: string;
    ageOfAsset?: string;
    sellerShortDescr?: string;
    secondAsset?: string;
    secondVechicleNoPrefix?: string;
    secondVechicleNo?: string;
    secondChassisNumber?: string;
    agricultureProof?: string;
    fcExpiryDate?: string;
    vehicleRegDate?: string;
    gvw?: string;
    reRegisteredVechicle?: string;
    interStateVehicle?: string;
    duplicateRC?: string;
    cubicCapacity?: string;
    seatingCapacity?: string;
    existingVechicleOwned?: string;
    noOfVehicles?: string;
    existingSelfCostAsset?: string;
    total?: string;
    make?: string;
    model?: string;
    year?: string;
    registeredOwner?: string;
    registeredOwnerName?: string;
    vhNoPrefix?: string;
    vhNumber?: string;
    costOfVehicle?: string;
} 

export interface PslData {
    activity?: string;
    propertyType?: string;
    detailActivity?: string;
    goodsManufactured?: string;
    typeOfService?: string;
    purposeOfLoanAg?: string;
    purposeOfLoanMsme?: string;
    businessActivity?: string;
    landHolding?: string;
    landOwner?: string;
    relWithLandowner?: string;
    farmerType?: string;
    landAreaInAcres?: string;
    landProof?: string;
    landProofUpload?: string;
    loanAmount? : string,
    proofOfInvest?: string;
    investProofUpload?: string;
    nameOfCa?: string;
    nameOfCaFirm?: string;
    caRegisterNo?: string;
    udinNo?: string;
    caCertifiedAmount?: string;
    otherInvestmentCost?: string;
    totalInvestmentCost?: string;
    investInEquipment?: string;
    investPlantMachinery?: string;
    cityTier?: string;
    investmentSocialInfra?: string;
    investmentOtherBank?: string;
    totalInvestment?: string;
    propertyLocatedCity?: string;
    propertyLocation?: string;
    propertyPincode?: string;
    landAmount?: string;
    landCost?: string;
    constructionCost?: string;
    totalPropertyCost?: string;
    registrationCost?: string;
    pslConsiderCost?: string;
    pslCategoryAg?: string;
    pslCategoryMsme?: string;
    pslCategoryHos?: string;
    pslSubCategoryAg?: string;
    pslSubCategoryMsme?: string,
    pslCertificateAg?: string;
    pslCertificateMsme?: string;
    pslCertificateHos?: string;
    weakerSectionAg?: string;
    weakerSectionMsme?: string;
}